version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install pyyaml

  build:
    commands:
      - echo "Validating CloudFormation template structure..."
      - python test.py
